name: Feature Request
description: Request creation of or support for a new feature.
title: "[Request]: "
labels: ["suggestion"]
body:
  - type: dropdown
    id: theme
    attributes:
      label: Which theme(s) does this apply to?
      description: >-
        If you select other, be sure to explain in the next field what theme you
        are using.
      multiple: true
      options:
        - 9anime
        - Agile
        - Blackout
        - Brink
        - Clarified
        - Clarity
        - Kure
        - Puni
        - Tilt
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is your desired feature/change?
      description: A clear and concise description of what you want changed or added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why should this be added?
      description: Any reasoning you have for this addition. This field is optional.
      placeholder: e.x "this will improve user experience"
  - type: textarea
    attributes:
      label: Additional notes
      description: >-
        Add any other context or screenshots about the feature request here. If
        you have suggestions on implementation, please place them here.
